### ISSUE TITLE
Tabs or Spaces? ;-)

### ISSUE THREAD

**Issue by suelje** [edenspiekermann/ama#3]

**Comment by nburkley** [comment]
An Edenspiekerman we don't really have a standard tech stack. We believe in choosing the right tool for the job. As such, we generally let our teams define their own code-style standards per project.

However, I think one of the things we generally agree on is setting our editors to use soft-tabs, set to two spaces.

**Comment by HugoGiraudel** [comment]
We almost all agree on 2-spaces indentation.

**Comment by maxhoffmann** [comment]
My two cents on this: If GitHub and every other tool displaying source code showed tabs as two spaces no one would care about using spaces for indentation. Tabs have a single purpose: It’s a character to describe one level of indentation. With tabs in the sourcecode implementing a custom indentation is trivial so tools could allow setting indentation width however you like.

Programmers are strange though and for some reason decided show tabs as *8* spaces by default in most applications (wtf?), insert a certain number of spaces when hitting the tab key instead of the tab character by default and implemented fairly complicated indentation algorithms inside of compilers that figure out how many spaces are used inside of a file for indentation. With other words a lot of work went into using something more complicated, which now has a better UX than the actual simple solution. ¯\_(ツ)_/¯

My opinion on any code style: use what the team uses. If you build a team, decide it once to end all future bikeshedding.

**Comment by HugoGiraudel** [comment]
Adding to the discussion, and joining map on the conclusion: pick whatever you like, as long as you are consistent across team members and projects. Don't switch from spaces to tabs, from 2 to 4. Pick one, and stick it. You don't even have to justify it. At some point it can be a matter of preference only. Just be consistent with it.
