### ISSUE TITLE
What’s your opinion on remote work?

### ISSUE THREAD

**Issue by anselmh** [edenspiekermann/ama#8]
I wonder what’s the opinion on working remote at edenspiekermann. Is this possible? Do you embrace it? Do you prefer people being on-site? Do you have experience with remote workers? Any advice, tips, problems with it? Do you limit it or differentiate your opinion for different jobs (a manager different from a developer or a designer)?

I’d love to have some insights on this.

**Comment by martzoukos** [comment]
Hello Anselm,

thank you for posting this and sorry for the late reply.
To answer your question, we prefer people working on-site as we have seen that the communication overhead of a remote set up is quite big and it can add up, sprint after sprint.

We work in an agile way for our digital products, particularly in Scrum, and that means that:
- the importance of building a team that works well together
- the presence of every team member in the daily standups and planning meetings (which take place for 1 full day every 2 weeks)
- the possibility of having two interdisciplinary professionals working together in front of a screen
are very crucial parts of our process. And sometimes you just have to yell something at your coworker while she/he's walking on the corridor and these small missed opportunites can add up in crucial moments.

I'm not saying that it's impossible to work otherwise, there are tools to achieve the above with remote team members, but the effort of setting them up and having people rely on them could sometimes be disruptive to the process.

**Comment by anselmh** [comment]
Thank you for the information. :)
