### ISSUE TITLE
Is edenspiekermann hiring freelancers as well?

### ISSUE THREAD

**Issue by anselmh** [edenspiekermann/ama#9]
I’m wondering if edenspiekermann is regularly working with freelancers or if you do everything in house. If you do, what’s your requirement, what do you expect from freelancers and how do you work together with them? When do you hire them (when things are going wrong or in advance of a project)?

**Comment by sdietrichberlin** [comment]
Hi Anselm, of course there are situations where we work with freelancers. Be it because we have a short-term need or can't cover some very specific area of expertise right away. We like to have freelancers work closely with us here on site for full sprints since we're working fully agile. Generally we hire people when they are a good fit to our team, skill-set and client base. If they know us and we know them for some time from a freelance relationship even better. 

Hope this helps.

Sebastian

**Comment by anselmh** [comment]
Thanks! :)
